App\Entity\Juego:
    attributes:
        id:
            groups: ['juego_lista']
        nombre:
            groups: ['juego_lista']
        baseExpansion:
            groups: ['juego_lista']
        juegoBase:
            groups: ['juego_lista']
        tipo:
            groups: ['juego_lista']
        autores:
            groups: ['juego_lista']
        descripcion:
            groups: ['juego_lista']
        precio:
            groups: ['juego_lista']
        editorialMadre:
            groups: ['juego_lista']
        editorialLocal:
            groups: ['juego_lista']
        dispAutoma:
            groups: ['juego_lista']
        minJugadores:
            groups: ['juego_lista']
        maxJugadores:
            groups: ['juego_lista']
        
App\Entity\Autor:
    attributes:
        id:
            groups: ['juego_lista']
        nombre:
            groups: ['juego_lista']


    