App\Entity\Jugador:
    attributes:
        id:
            groups: ['jugador_lista', jugador_ganadas, jugador_juegos]
        nombre:
            groups: ['jugador_lista', jugador_ganadas, jugador_juegos]
        correo:
            groups: ['jugador_lista']
        rol:
            groups: ['jugador_lista']
        fechaRegistro:
            groups: ['jugador_lista']
        password:
            groups: ['jugador_lista']
        partidas:
            groups: ['jugador_lista']
        partidasGanadas:
            groups: ['jugador_lista', jugador_ganadas]

App\Entity\Partida:
    attributes:
        id:
            groups: ['jugador_lista', jugador_ganadas]
        juego:
            groups: [jugador_ganadas. jugador_ganadas]
        fecha:
            groups: [jugador_ganadas, jugador_ganadas]
App\Entity\Juego:
    attributes:
        id:
            groups: [jugador_juegos]
        nombre:
            groups: [jugador_juegos]
        descripcion:
            groups: [jugador_juegos]



          
